### ISSUE TITLE
Can't find header

### ISSUE THREAD

**Issue by aodhol** [kylef-archive/KFData#70]
Since installing 1.1.1 my build fails on: 'KFData.h file not found'. 

I tried variations:

`#import "KFData.h"`
`#import <KFData/KFData.h>`

I noticed that it was removed on the basis that Cocoapods automatically generates the header? Is there something special I need to do to make it see the lib?

Thanks,

Aodh

n.b. we're not using use_frameworks (for various legacy reasons).

**Comment by Orgmir** [comment]
Hey, I'm currently working on a really old app that uses this library. It seems development on this has stopped, but I solved this issue by manually importing the separate headers that the `#import <KFData/KFData.h>` should have:

```obj-c
#import <KFData/KFAttribute.h>
#import <KFData/KFObjectManager.h>
#import <KFData/NSManagedObject+KFDataManager.h>
#import <KFData/NSManagedObjectContext+KFData.h>
```

**Comment by kylef** [comment]
I think that it should work with either `use_frameworks!` or a modern version of CocoaPods. If you're having difficulties you can use version 1.1.0 of KFData, the only different between 1.1.0 and 1.1.1 is the KFData framework header.

> It seems development on this has stopped

Yes that is right, but happy to review/merge/release any fixes that make sense via PR. `NSPersistentStoreContainer` in later versions of iOS replace KFDataStore, and [QueryKit](https://github.com/QueryKit/QueryKit) can replace KFAttribute/KFObjectManager.

**Comment by Orgmir** [comment]
Thank you for the response @kylef, I actually tried with `use_frameworks!` and I'm using cocoapods 1.3.1 also, I think its the latest version.

My project is Obj-C only, so I think cocoapods doesn't generate the header file. I think that only happens for Swift projects trying to use Obj-C libraries, cocoapods helps you out by creating the necessary headers and configuration to import the project.

**Comment by kylef** [comment]
@Orgmir Using 1.1.0 of KFData solved the problem?

**Comment by Orgmir** [comment]
Yes! You can close this issue I think :)

**Comment by kylef** [comment]
I've updated the README in 99b63b038e0e3d0cac21b95b7717668b7b2cf610 which adds a note on installation and also explains that NSPersistentContainer has replaced the need KFData in iOS 10 and macOS 10.12.

**Comment by kylef** [comment]
Additional Note: If anyone knows how to make the library work as a framework and a static library for CocoaPods with the framework header feel free to make a pull request and I will make a release.
